CREATE TABLE [dbo].[CodeSystems] (
    [id]                           INT             NOT NULL,
    [edsm_id]                      NVARCHAR (MAX)  NULL,
    [name]                         NVARCHAR (MAX)  NULL,
    [x]                            DECIMAL (10, 5) NULL,
    [y]                            DECIMAL (10, 5) NULL,
    [z]                            DECIMAL (10, 5) NULL,
    [population]                   NVARCHAR (MAX)  NULL,
    [is_populated]                 NVARCHAR (MAX)  NULL,
    [government_id]                NVARCHAR (MAX)  NULL,
    [government]                   NVARCHAR (MAX)  NULL,
    [allegiance]                   NVARCHAR (MAX)  NULL,
    [security_id]                  NVARCHAR (MAX)  NULL,
    [security]                     NVARCHAR (MAX)  NULL,
    [primary_economy_id]           NVARCHAR (MAX)  NOT NULL,
    [primary_economy]              NVARCHAR (MAX)  NULL,
    [power]                        NVARCHAR (MAX)  NULL,
    [power_state]                  NVARCHAR (MAX)  NULL,
    [power_state_id]               NVARCHAR (MAX)  NULL,
    [needs_permit]                 NVARCHAR (MAX)  NULL,
    [updated_at]                   NVARCHAR (MAX)  NULL,
    [simbad_ref]                   NVARCHAR (MAX)  NULL,
    [controlling_minor_faction_id] NVARCHAR (MAX)  NULL,
    [controlling_minor_faction]    NVARCHAR (MAX)  NULL,
    [reserve_type_id]              NVARCHAR (MAX)  NULL,
    [reserve_type]                 NVARCHAR (MAX)  NULL,
    [ed_system_address]            NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_CodeSystems] PRIMARY KEY CLUSTERED ([id] ASC)
);

