CREATE TABLE [dbo].[CodeModules] (
    [id]           INT            NOT NULL,
    [group_id]     INT            NOT NULL,
    [class]        NVARCHAR (MAX) NULL,
    [rating]       NVARCHAR (MAX) NULL,
    [price]        INT            NULL,
    [weapon_mode]  NVARCHAR (MAX) NULL,
    [missile_type] NVARCHAR (MAX) NULL,
    [name]         NVARCHAR (MAX) NULL,
    [belongs_to]   NVARCHAR (MAX) NULL,
    [ed_id]        NVARCHAR (MAX) NULL,
    [ed_symbol]    NVARCHAR (MAX) NULL,
    [game_context] NVARCHAR (MAX) NULL,
    [mass]         NVARCHAR (MAX) NULL,
    [ship]         NVARCHAR (MAX) NULL,
    [group]        NVARCHAR (MAX) NULL,
    [game_context_id] NVARCHAR(MAX) NULL, 
    [dps] NVARCHAR(MAX) NULL, 
    [power] NVARCHAR(MAX) NULL, 
    [damage] NVARCHAR(MAX) NULL, 
    [ammo] NVARCHAR(MAX) NULL, 
    [range_km] NVARCHAR(MAX) NULL, 
    [efficiency] NVARCHAR(MAX) NULL, 
    [power_produced] NVARCHAR(MAX) NULL, 
    [duration] NVARCHAR(MAX) NULL, 
    [cells] NVARCHAR(MAX) NULL, 
    [recharge_rating] NVARCHAR(MAX) NULL, 
    [capacity] NVARCHAR(MAX) NULL, 
    [count] NVARCHAR(MAX) NULL, 
    [rate] NVARCHAR(MAX) NULL, 
    [bins] NVARCHAR(MAX) NULL, 
    [additional_armour] NVARCHAR(MAX) NULL, 
    [vehicle_count] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_CodeModules] PRIMARY KEY ([id]) 
);

