IF NOT EXISTS (SELECT * FROM CodeServers)
BEGIN
SET IDENTITY_INSERT dbo.CodeServers ON
INSERT INTO CodeServers (id, ServerId) VALUES (1, '725880649356935192')
SET IDENTITY_INSERT dbo.CodeServers OFF
END