IF NOT EXISTS(SELECT 1 FROM VueFormFields WHERE FormKey = 'NewStory')
BEGIN
	INSERT INTO VueFormFields (FormKey, FieldSchema, ActionLink, IsActive) VALUES ('NewStory', '{"fields": [{"type": "input", "inputType": "text", "label": "Item Type Id", "model": "typeId", "inputName": "typeId", "readonly": true, "disabled": true, "default": "1", "visible": false}, {"type": "input", "inputType": "text", "label": "Story Title", "model": "title", "inputName": "title", "readonly": false, "featured": true, "required": true, "disabled": false, "placeholder": "Title Name"}, {"type": "textArea", "inputType": "text", "label": "Story", "model": "story", "inputName": "story", "required": true, "placeholder": "Story..."}, {"type": "input", "inputType": "text", "label": "Server ID:", "model": "ServerId", "inputName": "serverId", "readonly": false, "featured": true, "required": true, "disabled": false, "placeholder": "Server Id..."}, {"type": "input", "inputType": "text", "label": "Discord User ID: ", "model": "discordUserId", "inputName": "discordUserId", "featured": true, "required": true, "placeholder": "User ID..."}, {"type": "submit", "label": "", "buttonText": "Submit"}]}', 'submititem', 1)
END
ELSE
BEGIN
	UPDATE VueFormFields SET FieldSchema = '{"fields": [{"type": "input", "inputType": "text", "label": "Item Type Id", "model": "typeId", "inputName": "typeId", "readonly": true, "disabled": true, "default": "1", "visible": false}, {"type": "input", "inputType": "text", "label": "Story Title", "model": "title", "inputName": "title", "readonly": false, "featured": true, "required": true, "disabled": false, "placeholder": "Title Name"}, {"type": "textArea", "inputType": "text", "label": "Story", "model": "story", "inputName": "story", "required": true, "placeholder": "Story..."}, {"type": "input", "inputType": "text", "label": "Server ID:", "model": "ServerId", "inputName": "serverId", "readonly": false, "featured": true, "required": true, "disabled": false, "placeholder": "Server Id..."}, {"type": "input", "inputType": "text", "label": "Discord User ID: ", "model": "discordUserId", "inputName": "discordUserId", "featured": true, "required": true, "placeholder": "User ID..."}, {"type": "submit", "label": "", "buttonText": "Submit"}]}', ActionLink = 'submititem', IsActive = 1 WHERE FormKey = 'NewStory'
END

IF NOT EXISTS(SELECT 1 FROM VueFormFields WHERE FormKey = 'NewWisdom')
BEGIN
	INSERT INTO VueFormFields (FormKey, FieldSchema, ActionLink, IsActive) VALUES ('NewWisdom', '{"fields": [{"type": "input", "inputType": "text", "label": "Item Type Id", "model": "typeId", "inputName": "typeId", "readonly": true, "disabled": true, "default": "2", "visible": false}, {"type": "textArea", "inputType": "text", "label": "Wisdom", "model": "story", "inputName": "story", "required": true, "placeholder": "Wisdom..."}, {"type": "input", "inputType": "text", "label": "Server ID:", "model": "ServerId", "inputName": "serverId", "readonly": false, "featured": true, "required": true, "disabled": false, "placeholder": "Server Id..."}, {"type": "input", "inputType": "text", "label": "Discord User ID: ", "model": "discordUserId", "inputName": "discordUserId", "featured": true, "required": true, "placeholder": "User ID..."}, {"type": "submit", "label": "", "buttonText": "Submit"}]}', 'submititem', 1)
END
ELSE
BEGIN
	UPDATE VueFormFields SET FieldSchema = '{"fields": [{"type": "input", "inputType": "text", "label": "Item Type Id", "model": "typeId", "inputName": "typeId", "readonly": true, "disabled": true, "default": "2", "visible": false}, {"type": "textArea", "inputType": "text", "label": "Wisdom", "model": "story", "inputName": "story", "required": true, "placeholder": "Wisdom..."}, {"type": "input", "inputType": "text", "label": "Server ID:", "model": "ServerId", "inputName": "serverId", "readonly": false, "featured": true, "required": true, "disabled": false, "placeholder": "Server Id..."}, {"type": "input", "inputType": "text", "label": "Discord User ID: ", "model": "discordUserId", "inputName": "discordUserId", "featured": true, "required": true, "placeholder": "User ID..."}, {"type": "submit", "label": "", "buttonText": "Submit"}]}', ActionLink = 'submititem', IsActive = 1 WHERE FormKey = 'NewWisdom'
END

IF NOT EXISTS(SELECT 1 FROM VueFormFields WHERE FormKey = 'LoginForm')
BEGIN
	INSERT INTO VueFormFields (FormKey, FieldSchema, ActionLink, IsActive) VALUES ('LoginForm', '{"fields":[{"type":"input","inputType":"text","label":"Username: ","model":"username","inputName":"username","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Username..."},{"type":"Password","label":"Password: ","model":"password","inputName":"password","required":true,"placeholder":"Password...","showButton":true},{"type":"submit","label":"","buttonText":"Submit"}]}', 'login', 1)
END
ELSE
BEGIN
	UPDATE VueFormFields SET FieldSchema = '{"fields":[{"type":"input","inputType":"text","label":"Username: ","model":"username","inputName":"username","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Username..."},{"type":"Password","label":"Password: ","model":"password","inputName":"password","required":true,"placeholder":"Password...","showButton":true},{"type":"submit","label":"","buttonText":"Submit"}]}', ActionLink = 'login', IsActive = 1 WHERE FormKey = 'LoginForm'
END

IF NOT EXISTS(SELECT 1 FROM VueFormFields WHERE FormKey = 'RegisterForm')
BEGIN
	INSERT INTO VueFormFields (FormKey, FieldSchema, ActionLink, IsActive) VALUES ('RegisterForm', '{"fields":[{"type":"input","inputType":"text","label":"Account Name:","model":"accountName","inputName":"accountName","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Account Name..."},{"type":"input","inputType":"text","label":"Username: ","model":"username","inputName":"username","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Username..."},{"type":"input","inputType":"text","label":"First Name: ","model":"firstname","inputName":"firstname","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"First Name..."},{"type":"input","inputType":"text","label":"Last Name: ","model":"lastname","inputName":"lastname","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Last Name..."},{"type":"password","inputType":"password","label":"Password: ","model":"password","inputName":"password","required":true,"placeholder":"Password...","showButton":false},{"type":"password","inputType":"password","label":"Confirm Password: ","model":"confirmPassword","inputName":"confirmPassword","required":true,"placeholder":"Password...","showButton":false,"validator":"passwordValidation"},{"type":"input","inputType":"text","label":"Discord User ID: ","model":"discordUserId","inputName":"discordUserId","featured":true,"required":true,"placeholder":"User ID..."},{"type":"submit","label":"","buttonText":"Submit"}]}', 'register', 1)
END
ELSE
BEGIN
	UPDATE VueFormFields SET FieldSchema = '{"fields":[{"type":"input","inputType":"text","label":"Account Name:","model":"accountName","inputName":"accountName","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Account Name..."},{"type":"input","inputType":"text","label":"Username: ","model":"username","inputName":"username","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Username..."},{"type":"input","inputType":"text","label":"First Name: ","model":"firstname","inputName":"firstname","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"First Name..."},{"type":"input","inputType":"text","label":"Last Name: ","model":"lastname","inputName":"lastname","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Last Name..."},{"type":"password","inputType":"password","label":"Password: ","model":"password","inputName":"password","required":true,"placeholder":"Password...","showButton":false},{"type":"password","inputType":"password","label":"Confirm Password: ","model":"confirmPassword","inputName":"confirmPassword","required":true,"placeholder":"Password...","showButton":false,"validator":"passwordValidation"},{"type":"input","inputType":"text","label":"Discord User ID: ","model":"discordUserId","inputName":"discordUserId","featured":true,"required":true,"placeholder":"User ID..."},{"type":"submit","label":"","buttonText":"Submit"}]}', ActionLink = 'register', IsActive = 1 WHERE FormKey = 'RegisterForm'
END

IF NOT EXISTS(SELECT 1 FROM VueFormFields WHERE FormKey = 'RegisterUserForm')
BEGIN
	INSERT INTO VueFormFields (FormKey, FieldSchema, ActionLink, IsActive) VALUES ('RegisterUserForm', '{"fields":[{"type":"input","inputType":"text","label":"Username: ","model":"username","inputName":"username","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Username..."},{"type":"input","inputType":"text","label":"First Name: ","model":"firstname","inputName":"firstname","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"First Name..."},{"type":"input","inputType":"text","label":"Last Name: ","model":"lastname","inputName":"lastname","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Last Name..."},{"type":"password","inputType":"password","label":"Password: ","model":"password","inputName":"password","required":true,"placeholder":"Password...","showButton":false},{"type":"password","inputType":"password","label":"Confirm Password: ","model":"confirmPassword","inputName":"confirmPassword","required":true,"placeholder":"Password...","showButton":false,"validator":"passwordValidation"},{"type":"input","inputType":"text","label":"Discord User ID: ","model":"discordUserId","inputName":"discordUserId","featured":true,"required":true,"placeholder":"User ID..."},{"type":"submit","label":"","buttonText":"Submit"}]}', 'registeruser', 1)
END
ELSE
BEGIN
	UPDATE VueFormFields SET FieldSchema = '{"fields":[{"type":"input","inputType":"text","label":"Username: ","model":"username","inputName":"username","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Username..."},{"type":"input","inputType":"text","label":"First Name: ","model":"firstname","inputName":"firstname","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"First Name..."},{"type":"input","inputType":"text","label":"Last Name: ","model":"lastname","inputName":"lastname","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Last Name..."},{"type":"password","inputType":"password","label":"Password: ","model":"password","inputName":"password","required":true,"placeholder":"Password...","showButton":false},{"type":"password","inputType":"password","label":"Confirm Password: ","model":"confirmPassword","inputName":"confirmPassword","required":true,"placeholder":"Password...","showButton":false,"validator":"passwordValidation"},{"type":"input","inputType":"text","label":"Discord User ID: ","model":"discordUserId","inputName":"discordUserId","featured":true,"required":true,"placeholder":"User ID..."},{"type":"submit","label":"","buttonText":"Submit"}]}', ActionLink = 'registeruser', IsActive = 1 WHERE FormKey = 'RegisterUserForm'
END

IF NOT EXISTS(SELECT 1 FROM VueFormFields WHERE FormKey = 'ManageServer')
BEGIN
	INSERT INTO VueFormFields (FormKey, FieldSchema, ActionLink, IsActive) VALUES ('ManageServer', '{"fields": [{"type": "input", "inputType": "text", "label": "Id: ", "model": "Id", "inputName": "id", "readonly": true, "disabled": true, "visible": false}, {"type": "input", "inputType": "text", "label": "Account Id: ", "model": "AccountId", "inputName": "accountId", "readonly": true, "disabled": true, "visible": false}, {"type": "input", "inputType": "text", "label": "Nick Name:", "model": "Nickname", "inputName": "nickname", "readonly": false, "featured": true, "required": true, "disabled": false, "placeholder": "Server Nickname..."}, {"type": "input", "inputType": "text", "label": "Server ID:", "model": "ServerId", "inputName": "serverId", "readonly": false, "featured": true, "required": true, "disabled": false, "placeholder": "Server Id..."}, {"type": "checkbox", "label": "Enable Daily Wisdoms:", "model": "DailyWisdom", "default": true}, {"type": "submit", "label": "", "buttonText": "Submit"}]}', 'accountServers', 1)
END
ELSE
BEGIN
	UPDATE VueFormFields SET FieldSchema = '{"fields": [{"type": "input", "inputType": "text", "label": "Id: ", "model": "Id", "inputName": "id", "readonly": true, "disabled": true, "visible": false}, {"type": "input", "inputType": "text", "label": "Account Id: ", "model": "AccountId", "inputName": "accountId", "readonly": true, "disabled": true, "visible": false}, {"type": "input", "inputType": "text", "label": "Nick Name:", "model": "Nickname", "inputName": "nickname", "readonly": false, "featured": true, "required": true, "disabled": false, "placeholder": "Server Nickname..."}, {"type": "input", "inputType": "text", "label": "Server ID:", "model": "ServerId", "inputName": "serverId", "readonly": false, "featured": true, "required": true, "disabled": false, "placeholder": "Server Id..."}, {"type": "checkbox", "label": "Enable Daily Wisdoms:", "model": "DailyWisdom", "default": true}, {"type": "submit", "label": "", "buttonText": "Submit"}]}', ActionLink = 'accountServers', IsActive = 1 WHERE FormKey = 'ManageServer'
END

IF NOT EXISTS(SELECT 1 FROM VueFormFields WHERE FormKey = 'UpdatePassword')
BEGIN
	INSERT INTO VueFormFields (FormKey, FieldSchema, ActionLink, IsActive) VALUES ('UpdatePassword', '{"fields": [{"type": "input", "inputType": "text", "label": "User ID:", "model": "UserId", "inputName": "userId", "readonly": true, "featured": true, "required": true, "disabled": true, "visible": false, "placeholder": "User Id..."}, {"type": "password", "inputType": "password", "label": "Password: ", "model": "password", "inputName": "password", "required": true, "placeholder": "Password...", "showButton": false}, {"type": "password", "inputType": "password", "label": "Confirm Password: ", "model": "confirmPassword", "inputName": "confirmPassword", "required": true, "placeholder": "Password...", "showButton": false, "validator": "passwordValidation"}, {"type": "submit", "label": "", "buttonText": "Submit"}]}', 'resetPassword', 1)
END
ELSE
BEGIN
	UPDATE VueFormFields SET FieldSchema = '{"fields": [{"type": "input", "inputType": "text", "label": "User ID:", "model": "UserId", "inputName": "userId", "readonly": true, "featured": true, "required": true, "disabled": true, "visible": false, "placeholder": "User Id..."}, {"type": "password", "inputType": "password", "label": "Password: ", "model": "password", "inputName": "password", "required": true, "placeholder": "Password...", "showButton": false}, {"type": "password", "inputType": "password", "label": "Confirm Password: ", "model": "confirmPassword", "inputName": "confirmPassword", "required": true, "placeholder": "Password...", "showButton": false, "validator": "passwordValidation"}, {"type": "submit", "label": "", "buttonText": "Submit"}]}', ActionLink = 'resetPassword', IsActive = 1 WHERE FormKey = 'UpdatePassword'
END