IF NOT EXISTS(SELECT 1 FROM VueFormFields WHERE FormKey = 'NewStory')
BEGIN
	INSERT INTO VueFormFields (FormKey, FieldSchema, ActionLink, IsActive) VALUES ('NewStory', '{"fields":[{"type":"input","inputType":"text","label":"Item Type Id","model":"typeId","inputName":"typeId","readonly":true,"disabled":true,"default":"1", "visible":false},{"type":"input","inputType":"text","label":"Story Title","model":"title","inputName":"title","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Title Name"},{"type":"textArea","inputType":"text","label":"Story","model":"story","inputName":"story","required":true,"placeholder":"Story..."},{"type":"input","inputType":"email","label":"E-mail","model":"email","inputName":"email","placeholder":"Users e-mail address","required":true},{"type":"input","inputType":"email","label":"Confirm E-mail","model":"confirmEmail","inputName":"confirmEmail","placeholder":"Users e-mail address","required":true,"validator":"emailValidation"},{"type":"submit","label":"","buttonText":"Submit"}]}', '/api/submitstory', 1)
END

IF NOT EXISTS(SELECT 1 FROM VueFormFields WHERE FormKey = 'NewWisdom')
BEGIN
	INSERT INTO VueFormFields (FormKey, FieldSchema, ActionLink, IsActive) VALUES ('NewWisdom', '{"fields":[{"type":"input","inputType":"text","label":"Item Type Id","model":"typeId","inputName":"typeId","readonly":true,"disabled":true,"default":"2", "visible":false},{"type":"input","inputType":"text","label":"Wisdom Title","model":"title","inputName":"title","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Title Name..."},{"type":"textArea","inputType":"text","label":"Wisdom","model":"story","inputName":"story","required":true,"placeholder":"Wisdom..."},{"type":"input","inputType":"email","label":"E-mail","model":"email","inputName":"email","placeholder":"Users e-mail address","required":true},{"type":"input","inputType":"email","label":"Confirm E-mail","model":"confirmEmail","inputName":"confirmEmail","placeholder":"Users e-mail address","required":true,"validator":"emailValidation"},{"type":"submit","label":"","buttonText":"Submit"}]}', '/api/submitwisdom', 1)
END

IF NOT EXISTS(SELECT 1 FROM VueFormFields WHERE FormKey = 'LoginForm')
BEGIN
	INSERT INTO VueFormFields (FormKey, FieldSchema, ActionLink, IsActive) VALUES ('LoginForm', '{"fields":[{"type":"input","inputType":"text","label":"Username: ","model":"username","inputName":"username","readonly":false,"featured":true,"required":true,"disabled":false,"placeholder":"Username..."},{"type":"input","inputType":"text","label":"Password: ","model":"password","inputName":"password","required":true,"placeholder":"Password..."},{"type":"submit","label":"","buttonText":"Submit"}]}', '/api/login', 1)
END